var datos = {
	heladera_freezer: 	new Artefacto({codigo: 'heladera_freezer', 		tipo: Artefacto.TIPO_ELEC, consumo: 60.87, es24hs: true,}),
	cafetera_electrica: new Artefacto({codigo: 'cafetera_electrica',	tipo: Artefacto.TIPO_ELEC, consumo: 263, periodoHoras: 0.25}),
	horno_microondas: 	new Artefacto({codigo: 'horno_microondas', 		tipo: Artefacto.TIPO_ELEC, consumo: 234, periodoHoras: 0.25}),
	horno_gas: 			new Artefacto({codigo: 'horno_gas', 			tipo: Artefacto.TIPO_GAS,  consumo: 157}),
	hornalla_chica: 	new Artefacto({codigo: 'hornalla_chica', 		tipo: Artefacto.TIPO_GAS,  consumo: 39}),
	hornalla_mediana: 	new Artefacto({codigo: 'hornalla_mediana', 		tipo: Artefacto.TIPO_GAS,  consumo: 51}),
	hornalla_grande: 	new Artefacto({codigo: 'hornalla_grande', 		tipo: Artefacto.TIPO_GAS,  consumo: 78}),
	calefon_mediano: 	new Artefacto({codigo: 'calefon_mediano', 		tipo: Artefacto.TIPO_GAS,  consumo: 58.875}),
	batidora: 			new Artefacto({codigo: 'batidora', 				tipo: Artefacto.TIPO_ELEC, consumo: 37, periodoHoras: 0.25}),
	licuadora: 			new Artefacto({codigo: 'licuadora', 			tipo: Artefacto.TIPO_ELEC, consumo: 110, periodoHoras: 0.25}),
	procesadora: 		new Artefacto({codigo: 'procesadora', 			tipo: Artefacto.TIPO_ELEC, consumo: 146, periodoHoras: 0.25}),
	extractor_aire: 	new Artefacto({codigo: 'extractor_aire', 		tipo: Artefacto.TIPO_ELEC, consumo: 9}),
	calefactor_cocina: 	new Artefacto({codigo: 'calefactor_cocina', 	tipo: Artefacto.TIPO_GAS,  consumo: {3000c: 59, 4000c: 78, 5000c: 98}}),
	lampara_cocina: 	new Artefacto({codigo: 'lampara1_cocina', 		tipo: Artefacto.TIPO_ELEC, consumo: {5w: 9, 6w: 2, 8w: 2, 9w: x, 11w: x, 12w: x, 14w: x, 15w: x, 18w: x, 23w: x, 24w: x}}),
};